DROP TABLE IF EXISTS `sample`;
CREATE TABLE `sample` (
  `Code` varchar(4) NOT NULL default '',
  `Name` varchar(128) NOT NULL default '',
  `Abb` char(3) NOT NULL default ''
) TYPE=MyISAM;

INSERT INTO `sample` VALUES ('004', 'Afghanistan', 'AFG');
INSERT INTO `sample` VALUES ('248', 'Åland Islands', 'ALA');
INSERT INTO `sample` VALUES ('008', 'Albania', 'ALB');
INSERT INTO `sample` VALUES ('012', 'Algeria', 'DZA');
INSERT INTO `sample` VALUES ('016', 'American Samoa', 'ASM');
INSERT INTO `sample` VALUES ('020', 'Andorra', 'AND');
INSERT INTO `sample` VALUES ('024', 'Angola', 'AGO');
INSERT INTO `sample` VALUES ('660', 'Anguilla', 'AIA');
INSERT INTO `sample` VALUES ('028', 'Antigua and Barbuda', 'ATG');
INSERT INTO `sample` VALUES ('032', 'Argentina', 'ARG');
INSERT INTO `sample` VALUES ('051', 'Armenia', 'ARM');
INSERT INTO `sample` VALUES ('533', 'Aruba', 'ABW');
INSERT INTO `sample` VALUES ('036', 'Australia', 'AUS');
INSERT INTO `sample` VALUES ('040', 'Austria', 'AUT');
INSERT INTO `sample` VALUES ('031', 'Azerbaijan', 'AZE');
INSERT INTO `sample` VALUES ('044', 'Bahamas', 'BHS');
INSERT INTO `sample` VALUES ('048', 'Bahrain', 'BHR');
INSERT INTO `sample` VALUES ('050', 'Bangladesh', 'BGD');
INSERT INTO `sample` VALUES ('052', 'Barbados', 'BRB');
INSERT INTO `sample` VALUES ('112', 'Belarus', 'BLR');
INSERT INTO `sample` VALUES ('056', 'Belgium', 'BEL');
INSERT INTO `sample` VALUES ('084', 'Belize', 'BLZ');
INSERT INTO `sample` VALUES ('204', 'Benin', 'BEN');
INSERT INTO `sample` VALUES ('060', 'Bermuda', 'BMU');
INSERT INTO `sample` VALUES ('064', 'Bhutan', 'BTN');
INSERT INTO `sample` VALUES ('068', 'Bolivia', 'BOL');
INSERT INTO `sample` VALUES ('070', 'Bosnia and Herzegovina', 'BIH');
INSERT INTO `sample` VALUES ('072', 'Botswana', 'BWA');
INSERT INTO `sample` VALUES ('076', 'Brazil', 'BRA');
INSERT INTO `sample` VALUES ('092', 'British Virgin Islands', 'VGB');
INSERT INTO `sample` VALUES ('096', 'Brunei Darussalam', 'BRN');
INSERT INTO `sample` VALUES ('100', 'Bulgaria', 'BGR');
INSERT INTO `sample` VALUES ('854', 'Burkina Faso', 'BFA');
INSERT INTO `sample` VALUES ('108', 'Burundi', 'BDI');
INSERT INTO `sample` VALUES ('116', 'Cambodia', 'KHM');
INSERT INTO `sample` VALUES ('120', 'Cameroon', 'CMR');
INSERT INTO `sample` VALUES ('124', 'Canada', 'CAN');
INSERT INTO `sample` VALUES ('132', 'Cape Verde', 'CPV');
INSERT INTO `sample` VALUES ('136', 'Cayman Islands', 'CYM');
INSERT INTO `sample` VALUES ('140', 'Central African Republic', 'CAF');
INSERT INTO `sample` VALUES ('148', 'Chad', 'TCD');
INSERT INTO `sample` VALUES ('152', 'Chile', 'CHL');
INSERT INTO `sample` VALUES ('156', 'China', 'CHN');
INSERT INTO `sample` VALUES ('344', 'Hong Kong Special Administrative Region of China', 'HKG');
INSERT INTO `sample` VALUES ('446', 'Macao Special Administrative Region of China', 'MAC');
INSERT INTO `sample` VALUES ('170', 'Colombia', 'COL');
INSERT INTO `sample` VALUES ('174', 'Comoros', 'COM');
INSERT INTO `sample` VALUES ('178', 'Congo', 'COG');
INSERT INTO `sample` VALUES ('184', 'Cook Islands', 'COK');
INSERT INTO `sample` VALUES ('188', 'Costa Rica', 'CRI');
INSERT INTO `sample` VALUES ('384', 'Côte d\'Ivoire', 'CIV');
INSERT INTO `sample` VALUES ('191', 'Croatia', 'HRV');
INSERT INTO `sample` VALUES ('192', 'Cuba', 'CUB');
INSERT INTO `sample` VALUES ('196', 'Cyprus', 'CYP');
INSERT INTO `sample` VALUES ('203', 'Czech Republic', 'CZE');
INSERT INTO `sample` VALUES ('408', 'Democratic People\'s Republic of Korea', 'PRK');
INSERT INTO `sample` VALUES ('180', 'Democratic Republic of the Congo', 'COD');
INSERT INTO `sample` VALUES ('208', 'Denmark', 'DNK');
INSERT INTO `sample` VALUES ('262', 'Djibouti', 'DJI');
INSERT INTO `sample` VALUES ('212', 'Dominica', 'DMA');
INSERT INTO `sample` VALUES ('214', 'Dominican Republic', 'DOM');
INSERT INTO `sample` VALUES ('218', 'Ecuador', 'ECU');
INSERT INTO `sample` VALUES ('818', 'Egypt', 'EGY');
INSERT INTO `sample` VALUES ('222', 'El Salvador', 'SLV');
INSERT INTO `sample` VALUES ('226', 'Equatorial Guinea', 'GNQ');
INSERT INTO `sample` VALUES ('232', 'Eritrea', 'ERI');
INSERT INTO `sample` VALUES ('233', 'Estonia', 'EST');
INSERT INTO `sample` VALUES ('231', 'Ethiopia', 'ETH');
INSERT INTO `sample` VALUES ('234', 'Faeroe Islands', 'FRO');
INSERT INTO `sample` VALUES ('238', 'Falkland Islands (Malvinas)', 'FLK');
INSERT INTO `sample` VALUES ('242', 'Fiji', 'FJI');
INSERT INTO `sample` VALUES ('246', 'Finland', 'FIN');
INSERT INTO `sample` VALUES ('250', 'France', 'FRA');
INSERT INTO `sample` VALUES ('254', 'French Guiana', 'GUF');
INSERT INTO `sample` VALUES ('258', 'French Polynesia', 'PYF');
INSERT INTO `sample` VALUES ('266', 'Gabon', 'GAB');
INSERT INTO `sample` VALUES ('270', 'Gambia', 'GMB');
INSERT INTO `sample` VALUES ('268', 'Georgia', 'GEO');
INSERT INTO `sample` VALUES ('276', 'Germany', 'DEU');
INSERT INTO `sample` VALUES ('288', 'Ghana', 'GHA');
INSERT INTO `sample` VALUES ('292', 'Gibraltar', 'GIB');
INSERT INTO `sample` VALUES ('300', 'Greece', 'GRC');
INSERT INTO `sample` VALUES ('304', 'Greenland', 'GRL');
INSERT INTO `sample` VALUES ('308', 'Grenada', 'GRD');
INSERT INTO `sample` VALUES ('312', 'Guadeloupe', 'GLP');
INSERT INTO `sample` VALUES ('316', 'Guam', 'GUM');
INSERT INTO `sample` VALUES ('320', 'Guatemala', 'GTM');
INSERT INTO `sample` VALUES ('324', 'Guinea', 'GIN');
INSERT INTO `sample` VALUES ('624', 'Guinea-Bissau', 'GNB');
INSERT INTO `sample` VALUES ('328', 'Guyana', 'GUY');
INSERT INTO `sample` VALUES ('332', 'Haiti', 'HTI');
INSERT INTO `sample` VALUES ('336', 'Holy See', 'VAT');
INSERT INTO `sample` VALUES ('340', 'Honduras', 'HND');
INSERT INTO `sample` VALUES ('348', 'Hungary', 'HUN');
INSERT INTO `sample` VALUES ('352', 'Iceland', 'ISL');
INSERT INTO `sample` VALUES ('356', 'India', 'IND');
INSERT INTO `sample` VALUES ('360', 'Indonesia', 'IDN');
INSERT INTO `sample` VALUES ('364', 'Iran, Islamic Republic of', 'IRN');
INSERT INTO `sample` VALUES ('368', 'Iraq', 'IRQ');
INSERT INTO `sample` VALUES ('372', 'Ireland', 'IRL');
INSERT INTO `sample` VALUES ('376', 'Israel', 'ISR');
INSERT INTO `sample` VALUES ('380', 'Italy', 'ITA');
INSERT INTO `sample` VALUES ('388', 'Jamaica', 'JAM');
INSERT INTO `sample` VALUES ('392', 'Japan', 'JPN');
INSERT INTO `sample` VALUES ('400', 'Jordan', 'JOR');
INSERT INTO `sample` VALUES ('398', 'Kazakhstan', 'KAZ');
INSERT INTO `sample` VALUES ('404', 'Kenya', 'KEN');
INSERT INTO `sample` VALUES ('296', 'Kiribati', 'KIR');
INSERT INTO `sample` VALUES ('414', 'Kuwait', 'KWT');
INSERT INTO `sample` VALUES ('417', 'Kyrgyzstan', 'KGZ');
INSERT INTO `sample` VALUES ('418', 'Lao People\'s Democratic Republic', 'LAO');
INSERT INTO `sample` VALUES ('428', 'Latvia', 'LVA');
INSERT INTO `sample` VALUES ('422', 'Lebanon', 'LBN');
INSERT INTO `sample` VALUES ('426', 'Lesotho', 'LSO');
INSERT INTO `sample` VALUES ('430', 'Liberia', 'LBR');
INSERT INTO `sample` VALUES ('434', 'Libyan Arab Jamahiriya', 'LBY');
INSERT INTO `sample` VALUES ('438', 'Liechtenstein', 'LIE');
INSERT INTO `sample` VALUES ('440', 'Lithuania', 'LTU');
INSERT INTO `sample` VALUES ('442', 'Luxembourg', 'LUX');
INSERT INTO `sample` VALUES ('450', 'Madagascar', 'MDG');
INSERT INTO `sample` VALUES ('454', 'Malawi', 'MWI');
INSERT INTO `sample` VALUES ('458', 'Malaysia', 'MYS');
INSERT INTO `sample` VALUES ('462', 'Maldives', 'MDV');
INSERT INTO `sample` VALUES ('466', 'Mali', 'MLI');
INSERT INTO `sample` VALUES ('470', 'Malta', 'MLT');
INSERT INTO `sample` VALUES ('584', 'Marshall Islands', 'MHL');
INSERT INTO `sample` VALUES ('474', 'Martinique', 'MTQ');
INSERT INTO `sample` VALUES ('478', 'Mauritania', 'MRT');
INSERT INTO `sample` VALUES ('480', 'Mauritius', 'MUS');
INSERT INTO `sample` VALUES ('175', 'Mayotte', 'MYT');
INSERT INTO `sample` VALUES ('484', 'Mexico', 'MEX');
INSERT INTO `sample` VALUES ('583', 'Micronesia, Federated States of', 'FSM');
INSERT INTO `sample` VALUES ('492', 'Monaco', 'MCO');
INSERT INTO `sample` VALUES ('496', 'Mongolia', 'MNG');
INSERT INTO `sample` VALUES ('499', 'Montenegro', 'MNE');
INSERT INTO `sample` VALUES ('500', 'Montserrat', 'MSR');
INSERT INTO `sample` VALUES ('504', 'Morocco', 'MAR');
INSERT INTO `sample` VALUES ('508', 'Mozambique', 'MOZ');
INSERT INTO `sample` VALUES ('104', 'Myanmar', 'MMR');
INSERT INTO `sample` VALUES ('516', 'Namibia', 'NAM');
INSERT INTO `sample` VALUES ('520', 'Nauru', 'NRU');
INSERT INTO `sample` VALUES ('524', 'Nepal', 'NPL');
INSERT INTO `sample` VALUES ('528', 'Netherlands', 'NLD');
INSERT INTO `sample` VALUES ('530', 'Netherlands Antilles', 'ANT');
INSERT INTO `sample` VALUES ('540', 'New Caledonia', 'NCL');
INSERT INTO `sample` VALUES ('554', 'New Zealand', 'NZL');
INSERT INTO `sample` VALUES ('558', 'Nicaragua', 'NIC');
INSERT INTO `sample` VALUES ('562', 'Niger', 'NER');
INSERT INTO `sample` VALUES ('566', 'Nigeria', 'NGA');
INSERT INTO `sample` VALUES ('570', 'Niue', 'NIU');
INSERT INTO `sample` VALUES ('574', 'Norfolk Island', 'NFK');
INSERT INTO `sample` VALUES ('580', 'Northern Mariana Islands', 'MNP');
INSERT INTO `sample` VALUES ('578', 'Norway', 'NOR');
INSERT INTO `sample` VALUES ('275', 'Occupied Palestinian Territory', 'PSE');
INSERT INTO `sample` VALUES ('512', 'Oman', 'OMN');
INSERT INTO `sample` VALUES ('586', 'Pakistan', 'PAK');
INSERT INTO `sample` VALUES ('585', 'Palau', 'PLW');
INSERT INTO `sample` VALUES ('591', 'Panama', 'PAN');
INSERT INTO `sample` VALUES ('598', 'Papua New Guinea', 'PNG');
INSERT INTO `sample` VALUES ('600', 'Paraguay', 'PRY');
INSERT INTO `sample` VALUES ('604', 'Peru', 'PER');
INSERT INTO `sample` VALUES ('608', 'Philippines', 'PHL');
INSERT INTO `sample` VALUES ('612', 'Pitcairn', 'PCN');
INSERT INTO `sample` VALUES ('616', 'Poland', 'POL');
INSERT INTO `sample` VALUES ('620', 'Portugal', 'PRT');
INSERT INTO `sample` VALUES ('630', 'Puerto Rico', 'PRI');
INSERT INTO `sample` VALUES ('634', 'Qatar', 'QAT');
INSERT INTO `sample` VALUES ('410', 'Republic of Korea', 'KOR');
INSERT INTO `sample` VALUES ('498', 'Republic of Moldova', 'MDA');
INSERT INTO `sample` VALUES ('638', 'Réunion', 'REU');
INSERT INTO `sample` VALUES ('642', 'Romania', 'ROU');
INSERT INTO `sample` VALUES ('643', 'Russian Federation', 'RUS');
INSERT INTO `sample` VALUES ('646', 'Rwanda', 'RWA');
INSERT INTO `sample` VALUES ('654', 'Saint Helena', 'SHN');
INSERT INTO `sample` VALUES ('659', 'Saint Kitts and Nevis', 'KNA');
INSERT INTO `sample` VALUES ('662', 'Saint Lucia', 'LCA');
INSERT INTO `sample` VALUES ('666', 'Saint Pierre and Miquelon', 'SPM');
INSERT INTO `sample` VALUES ('670', 'Saint Vincent and the Grenadines', 'VCT');
INSERT INTO `sample` VALUES ('882', 'Samoa', 'WSM');
INSERT INTO `sample` VALUES ('674', 'San Marino', 'SMR');
INSERT INTO `sample` VALUES ('678', 'Sao Tome and Principe', 'STP');
INSERT INTO `sample` VALUES ('682', 'Saudi Arabia', 'SAU');
INSERT INTO `sample` VALUES ('686', 'Senegal', 'SEN');
INSERT INTO `sample` VALUES ('688', 'Serbia', 'SRB');
INSERT INTO `sample` VALUES ('690', 'Seychelles', 'SYC');
INSERT INTO `sample` VALUES ('694', 'Sierra Leone', 'SLE');
INSERT INTO `sample` VALUES ('702', 'Singapore', 'SGP');
INSERT INTO `sample` VALUES ('703', 'Slovakia', 'SVK');
INSERT INTO `sample` VALUES ('705', 'Slovenia', 'SVN');
INSERT INTO `sample` VALUES ('090', 'Solomon Islands', 'SLB');
INSERT INTO `sample` VALUES ('706', 'Somalia', 'SOM');
INSERT INTO `sample` VALUES ('710', 'South Africa', 'ZAF');
INSERT INTO `sample` VALUES ('724', 'Spain', 'ESP');
INSERT INTO `sample` VALUES ('144', 'Sri Lanka', 'LKA');
INSERT INTO `sample` VALUES ('736', 'Sudan', 'SDN');
INSERT INTO `sample` VALUES ('740', 'Suriname', 'SUR');
INSERT INTO `sample` VALUES ('744', 'Svalbard and Jan Mayen Islands', 'SJM');
INSERT INTO `sample` VALUES ('748', 'Swaziland', 'SWZ');
INSERT INTO `sample` VALUES ('752', 'Sweden', 'SWE');
INSERT INTO `sample` VALUES ('756', 'Switzerland', 'CHE');
INSERT INTO `sample` VALUES ('760', 'Syrian Arab Republic', 'SYR');
INSERT INTO `sample` VALUES ('762', 'Tajikistan', 'TJK');
INSERT INTO `sample` VALUES ('764', 'Thailand', 'THA');
INSERT INTO `sample` VALUES ('807', 'The former Yugoslav Republic of Macedonia', 'MKD');
INSERT INTO `sample` VALUES ('626', 'Timor-Leste', 'TLS');
INSERT INTO `sample` VALUES ('768', 'Togo', 'TGO');
INSERT INTO `sample` VALUES ('772', 'Tokelau', 'TKL');
INSERT INTO `sample` VALUES ('776', 'Tonga', 'TON');
INSERT INTO `sample` VALUES ('780', 'Trinidad and Tobago', 'TTO');
INSERT INTO `sample` VALUES ('788', 'Tunisia', 'TUN');
INSERT INTO `sample` VALUES ('792', 'Turkey', 'TUR');
INSERT INTO `sample` VALUES ('795', 'Turkmenistan', 'TKM');
INSERT INTO `sample` VALUES ('796', 'Turks and Caicos Islands', 'TCA');
INSERT INTO `sample` VALUES ('798', 'Tuvalu', 'TUV');
INSERT INTO `sample` VALUES ('800', 'Uganda', 'UGA');
INSERT INTO `sample` VALUES ('804', 'Ukraine', 'UKR');
INSERT INTO `sample` VALUES ('784', 'United Arab Emirates', 'ARE');
INSERT INTO `sample` VALUES ('826', 'United Kingdom of Great Britain and Northern Ireland', 'GBR');
INSERT INTO `sample` VALUES ('834', 'United Republic of Tanzania', 'TZA');
INSERT INTO `sample` VALUES ('840', 'United States of America', 'USA');
INSERT INTO `sample` VALUES ('850', 'United States Virgin Islands', 'VIR');
INSERT INTO `sample` VALUES ('858', 'Uruguay', 'URY');
INSERT INTO `sample` VALUES ('860', 'Uzbekistan', 'UZB');
INSERT INTO `sample` VALUES ('548', 'Vanuatu', 'VUT');
INSERT INTO `sample` VALUES ('862', 'Venezuela (Bolivarian Republic of)', 'VEN');
INSERT INTO `sample` VALUES ('704', 'Viet Nam', 'VNM');
INSERT INTO `sample` VALUES ('876', 'Wallis and Futuna Islands', 'WLF');
INSERT INTO `sample` VALUES ('732', 'Western Sahara', 'ESH');
INSERT INTO `sample` VALUES ('887', 'Yemen', 'YEM');
INSERT INTO `sample` VALUES ('894', 'Zambia', 'ZMB');
INSERT INTO `sample` VALUES ('716', 'Zimbabwe', 'ZWE');